apiVersion: v1
kind: Secret
metadata:
  name: lab-soat-secret-postgres
  namespace: lab-soat
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: cG9zdGdyZXM=
