apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab-local-storage
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/minikube/directory/structure/"
    type: DirectoryOrCreate
